language: node_js
node_js:
- '10'
branchs:
  only:
  - master
addons:
  ssh_known_hosts:
  - 47.101.52.166
before_install:
- openssl aes-256-cbc -K $encrypted_39d39f4899b9_key -iv $encrypted_39d39f4899b9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod -R 600 ~/.ssh/id_rsa
script:
- npm run docs:build
notifications:
  email:
    recipients:
    - 576359186@qq.com
    on_success: always
    on_failure: always
after_success:
- chmod -R 600 ~/.ssh/id_rsa
- cat ~/.ssh/id_rsa
- scp -o StrictHostKeyChecking=no -v -r docs/.vuepress/dist/* travis@47.101.52.166:/usr/blog
