---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: ie. post_import, post_publish
sections:
- type: directory
  path: blog
  label: blog
  create: all
  match: "**/*"
  exclude: md
  new_doc_ext: md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
